### ISSUE TITLE
Allow setting cache `VERSION`

### ISSUE THREAD

**Issue by mwarkentin** [ghickman/django-cache-url#14]
It would be nice if we could set the [cache version](https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-CACHES-VERSION) in the url.

Maybe something like `'hiredis:///unix/path/to/socket/file.sock/db[/prefix[:version]]'`

This would map closely with the keys that are generated: `"my-prefix:2:my-key"

I currently need to do the following: 

```python
CACHES = {'default': django_cache_url.config()}
CACHES['default']['VERSION'] = 2
```
Would this be something you're interested in adding?

**Comment by ghickman** [comment]
Addressed in #17, this is now available as a query argument: `?version=2`
