### ISSUE TITLE
Suggestion for URL schema

### ISSUE THREAD

**Issue by wengole** [ghickman/django-cache-url#16]
I've been trying to use this with redis socket and it will not work as documented.

Firstly using ```redis:///unix/path/to/redis.sock/db/prefix``` results in :unix as the path and generally a mess.

Secondly this method of specifying a socket rather than a TCP connection isn't very standard. Usually I see it as ```scheme:///path/to/socket/db``` This is used for example with MySQL connection URLs (```mysql:///var/lib/mysql/mysql.sock/test_database```). The tricky part comes with the optional prefix.

So here's my suggestion; move the prefix to a query resulting in the following:

```
scheme:///path/to/socket/db?prefix
```
Example:
```
redis:///var/run/redis/redis.sock/0?my_prefix
```

I can implement this for you along with (rewriting) the tests but wanted to run it by you first.

**Comment by ghickman** [comment]
Addressed in #17 and released in 1.0.0
