### ISSUE TITLE
Environs support

### ISSUE THREAD

**Issue by epicserve** [ghickman/django-cache-url#38]
@ghickman,

Any chance you would want to bring this back? Seems like people are moving away from https://pypi.org/project/django-environ/ in favor of https://github.com/sloria/environs. See this issue for more context, https://github.com/sloria/environs/issues/126.

**Comment by ghickman** [comment]
I'm not looking to bring this back myself I'm afraid.  If someone else would like to take it on I'd happily transition ownership of the repo and PyPI namespace to a new maintainer.

As you said [here](https://github.com/sloria/environs/issues/126#issuecomment-581590784):

> it's the least amount of work and I wouldn't have to support it.

This was my sentiment with deprecating in favour of django-environ 🙂

I'll close this issue but please feel free to reopen if you want to add more!

**Comment by epicserve** [comment]
@ghickman,

I've pushed the repo under my account and I've done the following.

* Brought back the readme
* Updated the tox config
* Updated the Travis config and got tests running and passing

If you wanted to give me access to publish to PyPI that would be great, then I could make a release.

Also, once that's done, maybe you could make a commit pointing people to the new location, https://github.com/epicserve/django-cache-url.

I would like to get a release made so I can make a PR to environs.

**Comment by ghickman** [comment]
> If you wanted to give me access to publish to PyPI

Absolutely, are you `epicserve` on there too?

**Comment by ghickman** [comment]
> make a commit pointing people to the new location

Done in 93451f3

Thanks for taking this on @epicserve!

**Comment by epicserve** [comment]
@ghickman,

I am epicserve on PyPi as well.

**Comment by epicserve** [comment]
@ghickman,

I made a couple of [releases](https://pypi.org/project/django-cache-url/).
